# helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}  # LoadBalancer
  ports:
  - port: {{ .Values.service.port }}  # 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
    