replicaCount: 2
image:
  repository: 905418041725.dkr.ecr.ap-south-1.amazonaws.com/dev-java-springboot
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilization: 80

service:
  type: LoadBalancer
  port: 80

persistentVolume:
  enabled: true
  size: 5Gi